### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [averstynen/CompositeHW#2]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote!

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by averstynen** [comment]
I added comments and documentation in new notebook

**Comment by luisortizuriarte** [comment]
You added many in-code comments which make your work easier to follow. Thanks. 

Closing issue now.
