### ISSUE TITLE
Tidying up after data exploration

### ISSUE THREAD

**Issue by luisortizuriarte** [averstynen/CompositeHW#5]
In your submitted notebook, you dedicate a lot of cells to exploratory analysis with various outputs printed out. As you work and start resolving your issues, either remove erroneous code or consolidate it into single cells with fewer printouts. This will help you avoid duplication and errors and make it easier to document as well.

**Comment by averstynen** [comment]
I submitted a new notebook that is cleaned up better.

**Comment by luisortizuriarte** [comment]
Your cleaned up notebook, in combination with improved documentation is much easier to follow. Closing this issue.
