### ISSUE TITLE
X axis labels in timeseries

### ISSUE THREAD

**Issue by luisortizuriarte** [averstynen/CompositeHW#6]
The labels in the plot in Out[13] run into each other, making it illegible. You can do this in a variety of ways, including calling the **matplotlib.pyplot.setp** 

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.setp.html

You can also call the **set_xticklabels** method:
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_xticklabels.html

**Comment by averstynen** [comment]
I angled the x-axis labels so they don't run into each other.

**Comment by luisortizuriarte** [comment]
This issue has been resolved. Closing.
