### ISSUE TITLE
Colormap choice for anomalies

### ISSUE THREAD

**Issue by luisortizuriarte** [averstynen/CompositeHW#7]
When plotting anomalies, it is more useful to use a diverging colormap rather than a sequential one. Take a look at the Matplotlib documentation for options:

https://matplotlib.org/stable/tutorials/colors/colormaps.html#sphx-glr-tutorials-colors-colormaps-py

**Comment by averstynen** [comment]
I changed my colormap choice to coolwarm

**Comment by luisortizuriarte** [comment]
Your choice of colormap is indeed more appropriate and the figures are much easier to interpret at a glance. Closing this issue.
