### ISSUE TITLE
Map projection

### ISSUE THREAD

**Issue by pdirmeyer** [averstynen/CompositeHW#8]
I know you are exploring to find a good map projection for California. Lambert Conformal may be a good choice - it is a favorite for limited-area maps in the mid-latitudes. But there are some parameter choices to make in order for it to look good. 

See: https://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#lambertconformal 

There is a good discussion about such projections with an example here: https://stackoverflow.com/questions/42237802/plotting-projected-data-in-other-projectons-using-cartopy

Also plenty more on stackoverflow - to get the map just right will take some _tinkering_.

**Comment by averstynen** [comment]
I ended up sticking with the same map projection.
